static_dir = "./static/"
log_dir = "/tmp/tts_logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
text_tokenizer_file = "hf://kyutai/tts-1.6b-en_fr/tokenizer_spm_8k_en_fr_audio.model"
batch_size = 32
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/tmp/tts_logs"
voice_folder = "hf-snapshot://kyutai/tts-voices/**/*.safetensors"
default_voice = "ears/p004/freeform_speech_01.wav"
hf_repo = "kyutai/tts-1.6b-en_fr"
cfg_coef = 2.0
cfg_is_no_text = true
padding_between = 1
interleaved_text_only = 0
n_q = 24
