static_dir = "./static/"
log_dir = "$HOME/tmp/tts-logs"
instance_name = "tts"
authorized_ids = ["public_token"]


# --- Text tokenizer (Kyutai TTS 0.75B EN) ---
text_tokenizer_file = "hf://kyutai/tts-0.75b-en-public/tokenizer_spm_8k_en_fr_audio.model"
text_card = 8000
existing_text_padding_id = 3
text_bos_token = 1
text_eos_token = 2
[modules.tts_py]
batch_size = 32
# Pin tokenizer and BOS for 0.75B EN model
text_tokenizer_file = "hf://kyutai/tts-0.75b-en-public/tokenizer_spm_8k_en_fr_audio.model"
text_bos_token = 1
type = "Py"
path = "/api/tts_streaming"

[modules.tts_py.py]
log_folder = "$HOME/tmp/moshi-server-logs"
voice_folder = "hf-snapshot://kyutai/tts-voices/**/*.safetensors"
default_voice = "unmute-prod-website/default_voice.wav"
cfg_coef = 2.0
cfg_is_no_text = true
padding_between = 1
n_q = 24
